import { useEffect, useRef, useState } from 'react'
import { FileImage, FileText, Plus, Trash2, UploadCloud } from 'lucide-react'
import { assetUrl } from '../../../shared/api/http'
import { PageHeader } from '../../../shared/components/PageHeader'
import { SAMPLE_FLOORPLAN_ID } from '../../../shared/constants'
import type { Floorplan } from '../domain/floorplan'
import { deleteFloorplan, listFloorplans, uploadFloorplan } from '../application/floorplanApi'

export function FloorplansPage() {
  const [items, setItems] = useState<Floorplan[]>([]); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null); const [file, setFile] = useState<File | null>(null); const inputRef = useRef<HTMLInputElement>(null)
  const refresh = async () => { setLoading(true); try { setItems(await listFloorplans()); setError(null) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudieron cargar los planos.') } finally { setLoading(false) } }
  useEffect(() => { void refresh() }, [])
  const onSubmit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); if (!file) { setError('Selecciona un archivo de plano.'); return } data.set('file', file); setSubmitting(true); try { await uploadFloorplan(data); form.reset(); setFile(null); await refresh() } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo subir el plano.') } finally { setSubmitting(false) } }
  const remove = async (id: string) => { if (!confirm('¿Eliminar este plano y su modelo asociado?')) return; await deleteFloorplan(id); await refresh() }
  return <div className="page"><PageHeader eyebrow="Administración" title="Planos" description="Carga y administra los planos base que se utilizarán para construir el mapa indoor." />{error && <div className="alert error">{error}</div>}<section className="source-layout"><form className="panel upload-panel" onSubmit={onSubmit}><div className="panel-heading"><div><span className="panel-kicker">Nuevo plano</span><h2>Subir floorplan</h2></div><Plus size={20} /></div><label className="dropzone" onClick={() => inputRef.current?.click()}><input ref={inputRef} type="file" accept=".png,.jpg,.jpeg,.webp,.svg,.pdf" hidden onChange={(e) => setFile(e.target.files?.[0] ?? null)} /><UploadCloud size={28} /><strong>{file ? file.name : 'Selecciona un plano'}</strong><span>PNG, JPG, SVG o PDF · máx. 20 MB</span></label><div className="field-grid"><label className="field"><span>Nombre</span><input name="name" placeholder="Plano principal" required /></label><label className="field"><span>Edificio</span><input name="building_name" placeholder="Clínica piloto" required /></label><label className="field"><span>Piso</span><input name="floor_label" placeholder="Piso 1" required /></label></div><button className="button primary" type="submit" disabled={submitting}>{submitting ? 'Subiendo…' : 'Agregar plano'}</button></form><section className="panel sources-panel"><div className="panel-heading"><div><span className="panel-kicker">Biblioteca</span><h2>{items.length} planos</h2></div></div>{loading ? <div className="empty-state">Cargando planos…</div> : items.length === 0 ? <div className="empty-state"><div className="empty-icon"><FileImage size={25} /></div><strong>Aún no hay planos</strong><span>Sube el primer floorplan para empezar a modelar.</span></div> : <div className="source-list">{items.map((item) => { const image = item.media_type.startsWith('image/'); return <article className="source-row" key={item.id}><div className="source-thumb">{image ? <img src={assetUrl(item.file_url)} alt="" /> : <FileText size={24} />}</div><div className="source-copy"><strong>{item.name} {item.id === SAMPLE_FLOORPLAN_ID && <em className="sample-badge">Ejemplo</em>}</strong><span>{item.building_name} · {item.floor_label}</span><small>{item.original_filename}</small></div><div className="source-type">{image ? <><FileImage size={14}/> Imagen</> : <><FileText size={14}/> PDF</>}</div>{item.id === SAMPLE_FLOORPLAN_ID ? <span className="sample-lock" title="Este plano se instala automáticamente como guía.">Demo</span> : <button className="icon-button danger" type="button" onClick={() => void remove(item.id)} title="Eliminar"><Trash2 size={17} /></button>}</article> })}</div>}</section></section></div>
}
